$teamSkin[0] = 'blank';
$teamSkin[1] = 'base';
$teamSkin[2] = 'baseb';
$teamSkin[3] = 'swolf';
$teamSkin[4] = 'dsword';
$teamSkin[5] = 'beagle';
$teamSkin[6] = 'cotp';

$teamName[0] = 'Unassigned';
$teamName[1] = 'Storm';
$teamName[2] = 'Inferno';
$teamName[3] = 'Star Wolf';
$teamName[4] = 'Diamond Sword';
$teamName[5] = 'Blood Eagle';
$teamName[6] = 'Phoenix';

$holoName[0] = "";
$holoName[1] = "Storm";
$holoName[2] = "Inferno";
$holoName[3] = "Starwolf";
$holoName[4] = "DSword";
$holoName[5] = "BloodEagle";
$holoName[6] = "Harbinger";
                  
$Host::AdminList = "";       // all players that will be automatically an admin upon joining server
$Host::SuperAdminList = "";  // all players that will be automatically a super admin upon joining server               
$Host::BindAddress = "";     // set to an ip address if the server wants to specify which NIC/IP to use                        
$Host::Port = 28000;
$Host::GameName = "Tribes 2 Server";
$Host::Password = "";
$Host::AdminPassword = "";
$Host::Dedicated = 0;
$Host::MissionType = "CTF";
$Host::Map = "Katabatic";
$Host::MaxPlayers = 64;
$Host::TimeLimit = 30;
$Host::BotCount = 2;
$Host::BotsEnabled = 0;
$Host::MinBotDifficulty = 0.5;
$Host::MaxBotDifficulty = 0.75;
$Host::Info = "This is a Tribes 2 Server.";
$Host::NoSmurfs = 0;
$Host::VoteTime = 20;               // amount of time before votes are calculated
$Host::VotePassPercent = 60;        // percent needed to pass a vote
$Host::KickBanTime = 300;           // specified in seconds
$Host::BanTime = 1800;              // specified in seconds
$Host::PlayerRespawnTimeout = 60;   // time before a dead player is forced into observer mode
$Host::warmupTime = 20;
$Host::TournamentMode = 0;
$Host::allowAdminPlayerVotes = 1;
$Host::FloodProtectionEnabled = 1;
$Host::MaxMessageLen = 120;
$Host::VoteSpread = 20;
$Host::TeamDamageOn = 0;

$MasterServerAddress = "IP:198.74.40.152:28000";

// 0: .v12 (1.2 kbits/sec), 1: .v24 (2.4 kbits/sec), 2: .v29 (2.9kbits/sec)
$Audio::maxEncodingLevel = 2;
$Audio::maxVoiceChannels = 2;

$Host::MapPlayerLimits["Abominable", "CnH"] = "-1 32";
$Host::MapPlayerLimits["AgentsOfFortune", "TeamHunters"] = "-1 32";
$Host::MapPlayerLimits["Archipelago", "CTF"] = "16 -1";
$Host::MapPlayerLimits["AshesToAshes", "CnH"] = "16 -1";
$Host::MapPlayerLimits["BeggarsRun", "CTF"] = "-1 16";
$Host::MapPlayerLimits["CasernCavite", "Hunters"] = "-1 32";
$Host::MapPlayerLimits["CasernCavite", "DM"] = "-1 32";
$Host::MapPlayerLimits["CasernCavite", "Bounty"] = "-1 24";
$Host::MapPlayerLimits["Damnation", "CTF"] = "-1 32";
$Host::MapPlayerLimits["DeathBirdsFly", "CTF"] = "32 -1";
$Host::MapPlayerLimits["Desiccator", "CTF"] = "16 -1";
$Host::MapPlayerLimits["DustToDust", "CTF"] = "-1 24";
$Host::MapPlayerLimits["DustToDust", "Hunters"] = "-1 32";
$Host::MapPlayerLimits["DustToDust", "TeamHunters"] = "-1 32";
$Host::MapPlayerLimits["Equinox", "CnH"] = "-1 32";
$Host::MapPlayerLimits["Equinox", "DM"] = "-1 32";
$Host::MapPlayerLimits["Escalade", "Hunters"] = "16 -1";
$Host::MapPlayerLimits["Escalade", "TeamHunters"] = "16 -1";
$Host::MapPlayerLimits["Escalade", "DM"] = "16 -1";
$Host::MapPlayerLimits["Escalade", "Bounty"] = "16 32";
$Host::MapPlayerLimits["Escalade", "Rabbit"] = "16 -1";
$Host::MapPlayerLimits["Firestorm", "CTF"] = "-1 24";
$Host::MapPlayerLimits["Firestorm", "CnH"] = "-1 24";
$Host::MapPlayerLimits["Flashpoint", "CnH"] = "16 -1";
$Host::MapPlayerLimits["Gehenna", "Hunters"] = "16 -1";
$Host::MapPlayerLimits["Gehenna", "TeamHunters"] = "16 -1";
$Host::MapPlayerLimits["Insalubria", "CnH"] = "-1 32";
$Host::MapPlayerLimits["JacobsLadder", "CnH"] = "-1 32";
$Host::MapPlayerLimits["Katabatic", "CTF"] = "-1 24";
$Host::MapPlayerLimits["Masada", "Siege"] = "-1 16";
$Host::MapPlayerLimits["Minotaur", "CTF"] = "-1 24";
$Host::MapPlayerLimits["Myrkwood", "Hunters"] = "-1 16";
$Host::MapPlayerLimits["Myrkwood", "DM"] = "-1 16";
$Host::MapPlayerLimits["Myrkwood", "Rabbit"] = "-1 24";
$Host::MapPlayerLimits["Oasis", "DM"] = "-1 16";
$Host::MapPlayerLimits["Overreach", "CnH"] = "16 -1";
$Host::MapPlayerLimits["Quagmire", "CTF"] = "16 -1";
$Host::MapPlayerLimits["Rasp", "TeamHunters"] = "-1 32";
$Host::MapPlayerLimits["Rasp", "Bounty"] = "-1 24";
$Host::MapPlayerLimits["Recalescence", "CTF"] = "16 -1";
$Host::MapPlayerLimits["Reversion", "CTF"] = "-1 32";
$Host::MapPlayerLimits["Rimehold", "Hunters"] = "16 -1";
$Host::MapPlayerLimits["Rimehold", "Hunters"] = "16 -1";
$Host::MapPlayerLimits["Riverdance", "CTF"] = "8 32";
$Host::MapPlayerLimits["Sanctuary", "CTF"] = "-1 32";
$Host::MapPlayerLimits["Sirocco", "CnH"] = "16 -1";
$Host::MapPlayerLimits["Slapdash", "CTF"] = "16 -1";
$Host::MapPlayerLimits["SunDried", "DM"] = "16 -1";
$Host::MapPlayerLimits["SunDried", "Bounty"] = "16 -1";
$Host::MapPlayerLimits["Talus", "Bounty"] = "-1 24";
$Host::MapPlayerLimits["ThinIce", "CTF"] = "-1 32";
$Host::MapPlayerLimits["Tombstone", "CTF"] = "8 32";
$Host::MapPlayerLimits["UltimaThule", "CTF"] = "-1 -1";
$Host::MapPlayerLimits["Underhill", "DM"] = "16 -1";
$Host::MapPlayerLimits["Underhill", "Bounty"] = "-1 24";
$Host::MapPlayerLimits["Whiteout", "DM"] = "16 -1";
$Host::MapPlayerLimits["Whiteout", "Bounty"] = "16 -1";
