addWebLink( "Tribes 2 Home Page", "www.tribes2.com" );
addWebLink( "T2 Technical Information", "sierrastudios.com/games/tribes2/support" );
addWebLink( "5 Assed Monkey", "www.5assedmonkey.com" );
addWebLink( "BarrysWorld", "www.barrysworld.com" );
addWebLink( "Clan Happytyme", "www.happytyme.com" );
addWebLink( "ClanBase", "www.clanbase.com" );
addWebLink( "Dopplegangers", "www.dopplegangers.com" );
addWebLink( "Dutchbat Homeworld", "www.dutchbat-homeworld.com" );
addWebLink( "Euro Tribesplayers", "www.euro-tribesplayers.com" );
addWebLink( "eXtreme-Players", "www.eXtreme-players.de" );
addWebLink( "Long Dongles", "www.longdongles.com" );
addWebLink( "MaxBaud.Net", "www.maxbaud.net" );
addWebLink( "NetGames UK", "www.nguk.net" );
addWebLink( "PlanetTribes", "www.planettribes.com" );
addWebLink( "Rogue Disciples", "www.roguedisciples.com" );
addWebLink( "StrikeForce", "www.strikeforcecenter.com" );
addWebLink( "TeamSound", "www.teamsound.com" );
addWebLink( "Telepresence Heavy Assault Team", "www.that.co.nz" );
addWebLink( "TribalWar", "www.tribalwar.com" );
addWebLink( "TribesMaps", "www.tribesmaps.com" );
addWebLink( "Tribes-Universe", "www.tribes-universe.com" );
addWebLink( "WirePlay", "www.wireplay.com.au" );
addWebLink( "IanStorm", "www.ianstorm.com" );
addWebLink( "Tribes2 Database", "www.tribes2database.com" );
//addWebLink( "Z Free", "games13.clear.net.nz" );